clusters:
- name: minikube
  destinationServer: https://kubernetes.default.svc
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"

    loki:
      enabled: true
      version: "0.39.3"

    promtrail:
      enabled: true
      version: "3.9.1"

    sampleApp:
      enabled: true
      branch: HEAD

    guestBookApp:
      enabled: true
      branch: HEAD

    wordpressApp:
      enabled: true
      branch: HEAD

#- name: gke
#  destinationServer:  https://EFD0D413B7FF216111BA4AD656EBA71F.gr7.us-east-1.eks.amazonaws.com
#  apps:
#    prometheus:
#      enabled: true
#      version: "9.7.4"
#    sampleApp:
#      enabled: true
#      branch: HEAD
